### ISSUE TITLE
Anatomical Pipeline: Segmentation output should be compressed

### ISSUE THREAD

**Issue by miykael** [miykael/fmriflows#2]
To reduce footprint, SPM's segmentation output should be compressed with a Gzip MapNode.

**Comment by PeerHerholz** [comment]
I'm on it. All tissue classes?

**Comment by miykael** [comment]
Yes. Should be a simple "add Gzip node" and connect that to datasink, I think :-)
Thanks for this. I'm currently on some new figures for after functional preprocessing. I think I have something cool ready by next week! And than I will start with the 1st level analysis.

**Comment by miykael** [comment]
Hey @PeerHerholz - I'm currently restructuring of the code. Taking care of many other issues. But before I touch this one, are you currently working on this or is it ok for you if I tackle it?

I hope to have a new, much more stable version (i.e. less refactoring of code) of `fmriflows` in 2-3 days.

**Comment by PeerHerholz** [comment]
Hey @miykael,

nah, sorry, I didn't manage to start working on this. However, if it's still there after your big update, I'll do it.
