### ISSUE TITLE
Error running workflow in 01_preproc_anat

### ISSUE THREAD

**Issue by StuartMcAfee** [miykael/fmriflows#27]
I'm exploring nipype as a means to implement our rsfMRI preprocessing in the near future, and am testing fmriflows with a small BIDS dataset to get a sense of how it works before I go about customizing containers. Unfortunately the workflow keeps failing at the antsRegistration stage, and I'm unsure of how to address the issue. Here is the error I'm seeing in the console:

> 190128-17:14:28,154 nipype.workflow INFO:
	 Workflow preproc_anat settings: ['check', 'execution', 'logging', 'monitoring']
190128-17:14:28,175 nipype.workflow INFO:
	 Running serially.
190128-17:14:28,176 nipype.workflow INFO:
	 [Node] Setting-up "preproc_anat.select_files" in "/workingdir/preproc_anat/_session_id_01_subject_id_102/select_files".
190128-17:14:28,179 nipype.workflow INFO:
	 [Node] Running "select_files" ("nipype.interfaces.utility.wrappers.Function")
190128-17:14:28,274 nipype.workflow INFO:
	 [Node] Finished "preproc_anat.select_files".
190128-17:14:28,275 nipype.workflow INFO:
	 [Node] Setting-up "preproc_anat.mainflow.reorient" in "/workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/reorient".
190128-17:14:28,277 nipype.workflow INFO:
	 [Node] Running "reorient" ("nipype.interfaces.image.Reorient")
190128-17:14:28,310 nipype.workflow INFO:
	 [Node] Finished "preproc_anat.mainflow.reorient".
190128-17:14:28,311 nipype.workflow INFO:
	 [Node] Setting-up "preproc_anat.mainflow.crop_FOV" in "/workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/crop_FOV".
190128-17:14:28,314 nipype.workflow INFO:
	 [Node] Running "crop_FOV" ("nipype.interfaces.fsl.utils.RobustFOV"), a CommandLine Interface with command:
robustfov -i /data/sub-102/ses-01/anat/sub-102_ses-01_highres-T1w.nii.gz -r sub-102_ses-01_highres-T1w_ROI.nii.gz -m sub-102_ses-01_highres-T1w_to_ROI.nii.gz
/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/grabbit/core.py:436: ResourceWarning: unclosed file <_io.TextIOWrapper name='/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/bids/layout/config/bids.json' mode='r' encoding='UTF-8'>
  domain = json.load(open(domain, 'r'))
190128-17:14:32,426 nipype.interface INFO:
	 stdout 2019-01-28T17:14:32.426646:Final FOV is: 
190128-17:14:32,427 nipype.interface INFO:
	 stdout 2019-01-28T17:14:32.426646:0.000000 176.000000 0.000000 256.000000 61.000000 170.000000 
190128-17:14:32,428 nipype.interface INFO:
	 stdout 2019-01-28T17:14:32.426646:
190128-17:14:32,484 nipype.workflow INFO:
	 [Node] Finished "preproc_anat.mainflow.crop_FOV".
190128-17:14:32,485 nipype.workflow INFO:
	 [Node] Setting-up "preproc_anat.mainflow.n4" in "/workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/n4".
190128-17:14:32,492 nipype.workflow INFO:
	 [Node] Running "n4" ("nipype.interfaces.ants.segmentation.N4BiasFieldCorrection"), a CommandLine Interface with command:
N4BiasFieldCorrection -d 3 --input-image /workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/crop_FOV/sub-102_ses-01_highres-T1w_ROI.nii.gz --output sub-102_ses-01_highres-T1w_ROI_corrected.nii.gz
190128-17:15:57,189 nipype.workflow INFO:
	 [Node] Finished "preproc_anat.mainflow.n4".
190128-17:15:57,190 nipype.workflow INFO:
	 [Node] Setting-up "preproc_anat.mainflow.gunzip" in "/workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/gunzip".
190128-17:15:57,196 nipype.workflow INFO:
	 [Node] Running "gunzip" ("nipype.algorithms.misc.Gunzip")
190128-17:15:57,473 nipype.workflow INFO:
	 [Node] Finished "preproc_anat.mainflow.gunzip".
190128-17:15:57,474 nipype.workflow INFO:
	 [Node] Setting-up "preproc_anat.mainflow.segment" in "/workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/segment".
190128-17:15:57,480 nipype.workflow INFO:
	 [Node] Running "segment" ("nipype.interfaces.spm.preprocess.NewSegment")
190128-17:20:30,601 nipype.workflow INFO:
	 [Node] Finished "preproc_anat.mainflow.segment".
190128-17:20:30,602 nipype.workflow INFO:
	 [Node] Setting-up "preproc_anat.mainflow.compressor" in "/workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/compressor".
190128-17:20:30,614 nipype.workflow INFO:
	 [Node] Running "compressor" ("nipype.interfaces.utility.wrappers.Function")
190128-17:20:32,192 nipype.workflow INFO:
	 [Node] Finished "preproc_anat.mainflow.compressor".
190128-17:20:32,193 nipype.workflow INFO:
	 [Node] Setting-up "preproc_anat.mainflow.extract_brain" in "/workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/extract_brain".
190128-17:20:32,199 nipype.workflow INFO:
	 [Node] Running "extract_brain" ("nipype.interfaces.utility.wrappers.Function")
190128-17:20:34,660 nipype.workflow INFO:
	 [Node] Finished "preproc_anat.mainflow.extract_brain".
190128-17:20:34,661 nipype.workflow INFO:
	 [Node] Setting-up "preproc_anat.mainflow.antsreg" in "/workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/antsreg".
190128-17:20:34,675 nipype.workflow INFO:
	 [Node] Running "antsreg" ("nipype.interfaces.ants.registration.Registration"), a CommandLine Interface with command:
antsRegistration --collapse-output-transforms 1 --dimensionality 3 --float 0 --initial-moving-transform [ /templates/mni_icbm152_nlin_asym_09c/template_brain_1.0_1.0_1.0.nii.gz, /workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/extract_brain/sub-102_ses-01_highres-T1w_ROI_corrected_brain.nii.gz, 1 ] --initialize-transforms-per-stage 0 --interpolation BSpline --output [ transform, transform_Warped.nii.gz, transform_InverseWarped.nii.gz ] --transform Rigid[ 0.01 ] --metric Mattes[ /templates/mni_icbm152_nlin_asym_09c/template_brain_1.0_1.0_1.0.nii.gz, /workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/extract_brain/sub-102_ses-01_highres-T1w_ROI_corrected_brain.nii.gz, 1, 32, Random, 0.15 ] --convergence [ 1000, 1e-06, 20 ] --smoothing-sigmas 4.0vox --shrink-factors 4 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform Affine[ 0.08 ] --metric Mattes[ /templates/mni_icbm152_nlin_asym_09c/template_brain_1.0_1.0_1.0.nii.gz, /workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/extract_brain/sub-102_ses-01_highres-T1w_ROI_corrected_brain.nii.gz, 1, 32, Regular, 0.15 ] --convergence [ 500x250x100, 1e-06, 20 ] --smoothing-sigmas 4.0x2.0x0.0vox --shrink-factors 4x2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform SyN[ 0.1, 3.0, 0.0 ] --metric Mattes[ /templates/mni_icbm152_nlin_asym_09c/template_brain_1.0_1.0_1.0.nii.gz, /workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/extract_brain/sub-102_ses-01_highres-T1w_ROI_corrected_brain.nii.gz, 1, 56, Regular, 0.25 ] --convergence [ 50x20, 1e-06, 10 ] --smoothing-sigmas 1.0x0.0vox --shrink-factors 2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 -v --winsorize-image-intensities [ 0.005, 0.995 ]  --write-composite-transform 1
190128-17:28:28,514 nipype.workflow WARNING:
	 [Node] Error on "preproc_anat.mainflow.antsreg" (/workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/antsreg)
190128-17:28:28,550 nipype.workflow ERROR:
	 Node antsreg.a0 failed to run on host a7e1d17d7382.
190128-17:28:28,634 nipype.workflow ERROR:
	 Saving crash info to /home/neuro/notebooks/crash-20190128-172828-neuro-antsreg.a0-885c3770-57a8-41b0-8a77-ae2c5b771e3c.pklz
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 48, in run
    node.run(updatehash=updatehash)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 369, in run
    runtime = self._run_interface(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/interfaces/ants/registration.py", line 940, in _run_interface
    runtime = super(Registration, self)._run_interface(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 752, in _run_interface
    self.raise_exception(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 689, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
antsRegistration --collapse-output-transforms 1 --dimensionality 3 --float 0 --initial-moving-transform [ /templates/mni_icbm152_nlin_asym_09c/template_brain_1.0_1.0_1.0.nii.gz, /workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/extract_brain/sub-102_ses-01_highres-T1w_ROI_corrected_brain.nii.gz, 1 ] --initialize-transforms-per-stage 0 --interpolation BSpline --output [ transform, transform_Warped.nii.gz, transform_InverseWarped.nii.gz ] --transform Rigid[ 0.01 ] --metric Mattes[ /templates/mni_icbm152_nlin_asym_09c/template_brain_1.0_1.0_1.0.nii.gz, /workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/extract_brain/sub-102_ses-01_highres-T1w_ROI_corrected_brain.nii.gz, 1, 32, Random, 0.15 ] --convergence [ 1000, 1e-06, 20 ] --smoothing-sigmas 4.0vox --shrink-factors 4 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform Affine[ 0.08 ] --metric Mattes[ /templates/mni_icbm152_nlin_asym_09c/template_brain_1.0_1.0_1.0.nii.gz, /workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/extract_brain/sub-102_ses-01_highres-T1w_ROI_corrected_brain.nii.gz, 1, 32, Regular, 0.15 ] --convergence [ 500x250x100, 1e-06, 20 ] --smoothing-sigmas 4.0x2.0x0.0vox --shrink-factors 4x2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 --transform SyN[ 0.1, 3.0, 0.0 ] --metric Mattes[ /templates/mni_icbm152_nlin_asym_09c/template_brain_1.0_1.0_1.0.nii.gz, /workingdir/preproc_anat/mainflow/_session_id_01_subject_id_102/extract_brain/sub-102_ses-01_highres-T1w_ROI_corrected_brain.nii.gz, 1, 56, Regular, 0.25 ] --convergence [ 50x20, 1e-06, 10 ] --smoothing-sigmas 1.0x0.0vox --shrink-factors 2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 1 -v --winsorize-image-intensities [ 0.005, 0.995 ]  --write-composite-transform 1
Standard output:

> 
> Standard error:
> 
> Return code: 137
> 
> 190128-17:28:28,640 nipype.workflow INFO:
> 	 ***********************************
> 190128-17:28:28,641 nipype.workflow ERROR:
> 	 could not run node: preproc_anat.mainflow.antsreg.a0
> 190128-17:28:28,643 nipype.workflow INFO:
> 	 crashfile: /home/neuro/notebooks/crash-20190128-172828-neuro-antsreg.a0-885c3770-57a8-41b0-8a77-ae2c5b771e3c.pklz
> 190128-17:28:28,643 nipype.workflow INFO:
> 	 ***********************************
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-40-935319b6b90e> in <module>
>       1 # Run the workflow in sequential mode
> ----> 2 res = preproc_anat.run('Linear')
> 
> /opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py in run(self, plugin, plugin_args, updatehash)
>     597         if str2bool(self.config['execution']['create_report']):
>     598             self._write_report_info(self.base_dir, self.name, execgraph)
> --> 599         runner.run(execgraph, updatehash=updatehash, config=self.config)
>     600         datestr = datetime.utcnow().strftime('%Y%m%dT%H%M%S')
>     601         if str2bool(self.config['execution']['write_provenance']):
> 
> /opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py in run(self, graph, config, updatehash)
>      69 
>      70         os.chdir(old_wd)  # Return wherever we were before
> ---> 71         report_nodes_not_run(notrun)
> 
> /opt/miniconda-latest/envs/neuro/lib/python3.7/site-packages/nipype/pipeline/plugins/tools.py in report_nodes_not_run(notrun)
>      80                 logger.debug(subnode._id)
>      81         logger.info("***********************************")
> ---> 82         raise RuntimeError(('Workflow did not execute cleanly. '
>      83                             'Check log for details'))
>      84 
> 
> RuntimeError: Workflow did not execute cleanly. Check log for details

The log has the following error message:

> Error! /home/neuro/notebooks/crash-20190128-172828-neuro-antsreg.a0-885c3770-57a8-41b0-8a77-ae2c5b771e3c.pklz is not UTF-8 encoded
> Saving disabled.
> See Console for more details.

I'm also a new python user, and I'd greatly appreciate any help or guidance, thank you!

**Comment by miykael** [comment]
Hi @StuartMcAfee,

It's great that you're using fmriflows. We're trying to finalize the software in the next few weeks to get the first official release out. So if you have any good inputs or recommendations, we're happy to hear how we can improve it for you!

@PeerHerholz, already pointed you to some nice toolboxes. But if you haven't yet, also check out [fmriprep](https://fmriprep.readthedocs.io/en/stable/).

If your question was answered, feel free to close this issue.

Cheers,
Michael

**Comment by StuartMcAfee** [comment]
Thank you @miykael ! 
I will close the issue now.

Cheers,
Stu
