### ISSUE TITLE
proposals for fmriflows logo

### ISSUE THREAD

**Issue by miykael** [miykael/fmriflows#4]
I have this nice image from the [parcellation_fragmenter project](https://github.com/miykael/parcellation_fragmenter):
![fmriflows_logo](https://user-images.githubusercontent.com/950321/44617015-9af46b80-a85b-11e8-8800-e2f06e20481f.png)

And I thought I could use this image (or somehting similar) as a logo for `fmriflows`. Together with a nice "flowing" font.

@ofgulban - You're a crafty designer! Would you have an idea and perhaps even the pleasure to create a logo? Because when I do it you get something like [this](https://github.com/miykael/LINEViewer/blob/master/lineviewer/static/LINEViewer_logo.png).

**Comment by ofgulban** [comment]
Hi Michael, I will have a look into this with pleasure :)

**Comment by miykael** [comment]
Cool, thanks! But no stress :-)

**Comment by miykael** [comment]
@PeerHerholz - what do you think about @ofgulban's logo proposals on the [gitter channel](https://gitter.im/fmriflows/Lobby)?

**Comment by PeerHerholz** [comment]
Oh boy, that's hard decision. 
1. @ofgulban should make a business out of his amazing skills!
2. I would say something from option 4 to 6, but would adapt the top left corner of the "fMRI" part as it extends beyond the brain in the background. I actually do like blurry transitions (based on my Bob Ross experience), but if option 4 is out, 5 or 6 are also fine.

**Comment by ofgulban** [comment]
Thanks, I have created a version 7, pushing the top left corner of `fMRI` part inside the brain following @PeerHerholz . It is the same document, have a look again. Once decided, i will push the svg version of the graphic so it can easily be edited in the future anyway.

**Comment by miykael** [comment]
Thanks @ofgulban - Having the `fMRI` inside the brain is top. I would go for this! And yes @PeerHerholz, Faruk should make a business out of this :+1:

**Comment by miykael** [comment]
Sorry for image overload. But which color gradient and number of parcels do you prefer?

I prefer `+z` (1,3), `+xz` (3,2) and `+yz` (3,3) as gradient direction.
And 2048 or 256 parcels.

**Comment by ofgulban** [comment]
I like 2048 parcels `+xz` & `-xz` because the central sulcus looks cool. 

@miykael can you produce a version of one of these images with [color cycling](
https://en.wikipedia.org/wiki/Color_cycling?wprov=sfti1). I can create an ever-flowing animation with `fmri flows` overlay if you provide the frames.

**Comment by PeerHerholz** [comment]
Do you mean something like this: https://twitter.com/miyka_el/status/1028027334245285889 ?

**Comment by ofgulban** [comment]
Yes. It would look smoother if the colormap is extended and mirrored though. So the red does not neighbour blue while cycling.

**Comment by miykael** [comment]
uiuiui... @ofgulban - that sounds super cool!
How do I create such an image with color cycling? Currently, I just create a PNG file with `nilearn`'s plotting function. PNG is about 1.5MB for about 8000x6000 and 40MB for SVG version.

**Comment by miykael** [comment]
For this to create a GIF, do you need one image and just have some information about the color cycle or do you nonetheless need multiple images, with each being at a different color phase?

**Comment by miykael** [comment]
Here the highres PNG files for...

## 2048 Parcels
![plot_gmm_pial_02048_xz](https://user-images.githubusercontent.com/950321/45488529-fa121580-b761-11e8-8648-3d1d45e94b52.png)

## 4096 Parcels
![plot_gmm_pial_04096_xz](https://user-images.githubusercontent.com/950321/45488530-fa121580-b761-11e8-8aa6-52d474929899.png)

## 8192 Parcels
![plot_gmm_pial_08192_xz](https://user-images.githubusercontent.com/950321/45488531-fa121580-b761-11e8-912f-3dd860f1c660.png)

**Comment by ofgulban** [comment]
@miykael I think many images with different colormap phase would be enough for creating the animation.

I have created a new version of the logo with 8192 parcels png. Have a look at it. For me it looks a bit too dark on the bottom part, so maybe this was not the best gradient direction.

**Comment by miykael** [comment]
@ofgulban how many different phases do you want for the animation? It takes some time to create them, but I'm happy to provide them.

I love the new 8192 parcels logo and I agree that it's a bit too dark at the bottom. I tried to find some new directions. What do you and @PeerHerholz think?

## Alternative 1
![plot_gmm_pial_8192_158651](https://user-images.githubusercontent.com/950321/45839257-230f4900-bd14-11e8-9163-ca9f963b2084.png)

## Alternative 2
![plot_gmm_pial_8192_22632](https://user-images.githubusercontent.com/950321/45839254-230f4900-bd14-11e8-8588-e07405e1232a.png)

## Alternative 3
![plot_gmm_pial_8192_23471](https://user-images.githubusercontent.com/950321/45839255-230f4900-bd14-11e8-8d41-f9d91e79fd11.png)

**Comment by ofgulban** [comment]
@miykael thanks michael I will update the latest version with these 3 alternatives.

For the gif, I would say 12 frames per second over 2 seconds could be a starting point. So 24 phases.
If needed we can make the animation slower and fill in the gaps later. I think for the initial animation we can make do with lower resolution images with less parcels.

**Comment by ofgulban** [comment]
I like 11 the most now.

**Comment by miykael** [comment]
Thanks, @ofgulban! I also like version 11 the most. @PeerHerholz, what do you think?

**Comment by miykael** [comment]
By the way, @ofgulban don't forget to add yourself and your affiliation to the [`.zenodo.json`](https://github.com/miykael/fmriflows/blob/master/.zenodo.json) file. I'm not sure if the final publication will be via zenodo, but it's clear that you will be on the paper!

**Comment by miykael** [comment]
@ofgulban - I might have gone a bit overboard with the cyclic animation. I created 256 images (each with 8192 parcels). It took 2h to create all figures per colormap, but I'm happy to create other ones if you're interested.

I found a good homepage that has some nice cyclic colormap examples, that you might also appreciate: https://nicoguaro.github.io/posts/cyclic_colormaps/

I tried to create some small gifs of 6 different colormaps. You can find all the figures in higher resolution, as well as the gifs [here](https://www.dropbox.com/sh/vgv7vw5iw4howcn/AAC3oQ3YOIx5Rbg2YajL7K3Na?dl=1):

## Spectral (with correction for tritanomaly)
![gif_spectral](https://user-images.githubusercontent.com/950321/46042882-cbf3e480-c116-11e8-8330-671964b0997c.gif)

## Twilight (with correction for tritanomaly)
![gif_twilight](https://user-images.githubusercontent.com/950321/46042883-cbf3e480-c116-11e8-839a-9f5a2fdd1020.gif)

## Colorwheel (with correction for tritanomaly)
![gif_colorwheel_tritanomaly](https://user-images.githubusercontent.com/950321/46042878-cb5b4e00-c116-11e8-9c26-8d46d8058360.gif)

## HSV (with correction for tritanomaly)
![gif_hsv_tritanomaly](https://user-images.githubusercontent.com/950321/46042880-cb5b4e00-c116-11e8-8ddf-92edf09f1f8a.gif)

## erdc_icefire (with correction for tritanomaly)
![gif_erdc_icefire_tritanomaly](https://user-images.githubusercontent.com/950321/46042879-cb5b4e00-c116-11e8-9455-5b5601010b6a.gif)

## nic_edge (with correction for tritanomaly)
![gif_nic_edge_tritanomaly](https://user-images.githubusercontent.com/950321/46042881-cb5b4e00-c116-11e8-80ef-cac45d74ac76.gif)

**Comment by ofgulban** [comment]
I am mesmerized. Thanks for the cyclic colormap link, I didn't know that site very cool. I like twilight, icefire and spectral. Spectral could be cooler to have it cyclic:
instead of `R----->B`, having it `R------>BB<-------R` it should be possible to to this mirroring with cmaps but I dont have time for it now.

I will create animated logo versions and lets see which one look the best together with the text. This might take some time due to my current schedule.

**Comment by ofgulban** [comment]
@miykael @PeerHerholz have a look at the animation [here](https://drive.google.com/open?id=1_jpdjrQmIneB1FphW2fPvzufGQl4Il-s).

You can try other animations as the underlay, a have tried a few but this one looked the best so far.

**Comment by miykael** [comment]
WOW :heart_eyes: that looks so cool @ofgulban - thank you for making this. I love `anim_02_overlaid.gif`. I prefer it over `anim_01` because it has much more an "updating" effect, where `anim_01` has a cyclic pulsing effect :-)

We will definitely use your gifs once we announce the software on twitter! I'm so excited! :-)

**Comment by ofgulban** [comment]
The bash script for creating the gif is there, you can try different inputs or for instance remove the optimization. Will look sharper but increase the files size.

I have created a separate overlay text in the `.svg` file. In case if you want to change colors of it etc. you can do it from there and export it as png.

**Comment by PeerHerholz** [comment]
@miykael, @ofgulban, this is nothing but awesome. 
+1 for `anim_02_overlaid.gif` 

At this point a set of different versions should be submitted to the OHBM art competition!

**Comment by miykael** [comment]
I'm all for OHBM art submission, but how? And which design? With the logo or without?

**Comment by miykael** [comment]
Closing this issue as @ofgulban created a great logo!
